global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['host.docker.internal:5000']  # For Mac/Windows
        labels:
          app: 'cloudsense-api'
      - targets: ['172.17.0.1:5000']  # For Linux
        labels:
          app: 'cloudsense-api'
